const {test}=require('node:test');const assert=require('node:assert/strict');const ts=require('typescript');const fs=require('node:fs');const vm=require('node:vm');
function load(){const calls=[];let valid=true;const deps={'next/headers':{cookies:async()=>({get:()=>undefined,set:(...v)=>calls.push(v),delete:()=>{}})},'@/lib/appwrite':{createAppwriteAccountClient:token=>({account:{get:async()=>{calls.push(token);if(!valid)throw Error('revoked');return {$id:'owner',email:'owner@example.com'}}}})},'@/lib/env':{isAppwriteConfigured:()=>true,getEnv:()=>({adminEmails:[]})}};const exp={};vm.runInNewContext(ts.transpileModule(fs.readFileSync('lib/auth.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{exports:exp,require:k=>deps[k],process:{env:{NODE_ENV:'production'}}});return {actions:exp,calls,revoke:()=>{valid=false}}}
test('legacy locally signed cookies are rejected',async()=>{const {actions,calls}=load();assert.equal(await actions.fetchAuthUser('contentos.v1.forged.signature'),null);assert.equal(calls.length,0)});
test('provider sessions are checked again and revoked sessions fail closed',async()=>{const {actions,revoke}=load();assert.equal((await actions.fetchAuthUser('provider-secret')).id,'owner');revoke();assert.equal(await actions.fetchAuthUser('provider-secret'),null)});
test('a user identity alone cannot create an authentication cookie',async()=>{const {actions}=load();await assert.rejects(actions.setAuthCookies({user:{id:'forged',email:'forged@example.com'}}))});
test('cookies use provider secret and secure HTTP-only attributes',async()=>{const {actions,calls}=load();await actions.setAuthCookies({accessToken:'provider-secret',user:{id:'owner',email:'owner@example.com'}});assert.equal(calls[0][1],'provider-secret');assert.equal(calls[0][2].httpOnly,true);assert.equal(calls[0][2].secure,true)});
function passwordLogin(response){const requests=[];const exp={};const deps={'node-appwrite':{},'@/lib/env':{getEnv:()=>({appwriteEndpoint:'https://example.appwrite.test/v1',appwriteProjectId:'project',appwriteApiKey:'must-not-be-sent'})}};vm.runInNewContext(ts.transpileModule(fs.readFileSync('lib/appwrite.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{exports:exp,require:k=>deps[k],AbortSignal,fetch:async(url,options)=>{requests.push(options);return response}});return {login:exp.createAppwritePasswordSession,requests}}
test('password login uses provider cookie without sending the privileged API key',async()=>{const {login,requests}=passwordLogin({ok:true,json:async()=>({userId:'owner',expire:'2030-01-01T00:00:00Z'}),headers:{getSetCookie:()=>['a_session_project_legacy=wrong; Path=/','a_session_project=real%3Dsecret; HttpOnly']}});assert.equal((await login('owner@example.com','password')).secret,'real=secret');assert.equal(requests[0].headers['X-Appwrite-Key'],undefined);assert.equal(requests[0].cache,'no-store')});
test('password login fails closed when only a legacy cookie is returned',async()=>{const {login}=passwordLogin({ok:true,json:async()=>({userId:'owner',expire:'2030-01-01T00:00:00Z'}),headers:{getSetCookie:()=>['a_session_project_legacy=wrong']}});await assert.rejects(login('owner@example.com','password'),/valid session/)});
test('password login does not expose provider error messages',async()=>{const {login}=passwordLogin({ok:false,status:401,json:async()=>({type:'user_invalid_credentials',message:'private provider details'})});await assert.rejects(login('owner@example.com','password'),e=>e.code===401&&!e.message.includes('private'))});
